version: "3.9"

services:

  backend:
    image: andresnenis/symfony-react-ec2-backend:latest
    container_name: backend
    networks:
      - symfony-net
    # No necesitamos exponer al exterior, React hará proxy interno
    restart: unless-stopped

  frontend:
    image: andresnenis/symfony-react-ec2-frontend:latest
    container_name: frontend
    ports:
      - "80:80"   # Aquí está React, será lo que ve el navegador
    depends_on:
      - backend
    networks:
      - symfony-net
    restart: unless-stopped

networks:
  symfony-net:
    driver: bridge