version: "3.9"

services:
  backend:
    image: andresnenis/symfony-react-ec2-backend:latest
    container_name: symfony-backend
    networks:
      - symfony-net

  frontend:
    image: andresnenis/symfony-react-ec2-frontend:latest
    container_name: react-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - symfony-net

networks:
  symfony-net:
    driver: bridge