version: "3.9"

services:

  backend:
    build: ./backend
    container_name: symfony-backend
    networks:
      - symfony-net

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - symfony-net

networks:
  symfony-net:
    driver: bridge